

SELECT EXTRACT(MONTH FROM TO_DATE('12/11/2019', 'DD/MM/YYYY')) FROM DUAL;

SELECT EXTRACT(MONTH FROM TO_DATE('12/11/2019', 'MM/DD/YYYY')) FROM DUAL;

SELECT TO_NUMBER('10') + 10 FROM DUAL;

SELECT TO_CHAR(1234.123,'9999') FROM DUAL;


SELECT TO_CHAR(1234.123,'9999,999') FROM DUAL;

SELECT NVL(10,0) FROM DUAL;


// RETORNA ZERO
SELECT NVL(NULL,0) FROM DUAL;



SELECT 
NVL(TV.NOME, 'NÃO ENCONTRADO') AS NOME_VE_VENDEDOR,
NVL(TV.BAIRRO, 'NÃO ENCONTRADO') AS NOME_BAIRRO_VENDEDOR,
NVL(TC.NOME, 'NÃO ENCONTRADO') AS NOME_CLIENTE,
NVL(TC.BAIRRO, 'NÃO ENCONTRADO') AS NOME_BAIRRO_CLIENTE
FROM 
TABELA_DE_VENDEDORES TV
FULL JOIN
TABELA_DE_CLIENTES TC
ON TV.BAIRRO  = TC.BAIRRO;