SELECT * FROM TB_CLIENTES;

SELECT * FROM TB_PRODUTOS;

SELECT   SABOR,  PRODUTO, TAMANHO, NOME,PRECO_LISTA, EMBALAGEM FROM TB_PRODUTOS;

SELECT   SABOR,  PRODUTO AS "CODIGO DO PRODUTO", TAMANHO, NOME AS "NOME DO PRODUTO",PRECO_LISTA, EMBALAGEM FROM TB_PRODUTOS;
