
// data

//to_char vai converter data em texto
//to_date vai converter texto em data
// SYSDATE HORA E O DIA ATUAL 
// MONTHS_BETWEEN - VOCE COLOCA DUAS DATA E ELE CALCULA O NUMERO DE MESES ENTRE ESSAS DATAS
// ADD_MONTHS - ADICIONAR NÚMERO DE MESES 
// NEXT_DAY A DATA PROXIMO DIA DA SEMANA EXEMPLO DISSER UMA DATA E A SEMANA ELE VAI RETORNAR A DATA CORREPODENTE A SEMANA.
// LAST_DAY O ULTIMO DIA DO MÊS
// TRUNC ELE VAI PEGAR UMA DATA HORAS E EXIBIR SOMENTE A DATA DIA MES E ANO
// ROUND ARRENDENDASSE A DATA 

// D- DIA DA SEMANA
// DD- DIA DO MÊS
// DDD-NÚMERO DO DIA NO ANO
// DAY - DIA POR EXTENSO

// MM- MÊS DO ANO
//MON - MÊS ABREVIADO
// MONTH - MÊS POR EXTENSO

//YYYY - ANO COM 4 DÍGITOS
//YY - ANO COM DOIS DÍGITOS

// HH - HORA COM DOIS DIGITOS
// HH12 - HORA DE 0 A 12
// HH24 - HORA DE 0 A 24
// MI MINUTO
//SS - SEGUNDO
// SÍMBOLO DE SEPARADOR DA DATA - / * ,/OU UM TEXTO QUALQUER

SELECT SYSDATE FROM DUAL;

SELECT TO_CHAR(SYSDATE,'DD/MM/YYYY HH:MI:SS') FROM DUAL;

SELECT NOME, DATA_DE_NASCIMENTO FROM TABELA_DE_CLIENTES;

SELECT NOME, TO_CHAR(DATA_DE_NASCIMENTO, 'DD MONTH YYYY, DAY') FROM TABELA_DE_CLIENTES;

SELECT SYSDATE + 127 FROM DUAL;


SELECT NOME,IDADE, TO_CHAR(DATA_DE_NASCIMENTO, 'DD MONTH YYYY, DAY') FROM TABELA_DE_CLIENTES;

// NUMERO DE MESES
SELECT NOME, IDADE, SYSDATE - DATA_DE_NASCIMENTO FROM TABELA_DE_CLIENTES;

// NUMERO DE ANOS
SELECT NOME, IDADE, (SYSDATE - DATA_DE_NASCIMENTO)/365 FROM TABELA_DE_CLIENTES;


SELECT NOME, IDADE,MONTHS_BETWEEN(SYSDATE, DATA_DE_NASCIMENTO)/12 FROM TABELA_DE_CLIENTES;

// PODE SER USADA PARA CALCULAR VECIMENTO DE UMA FATURA.
SELECT ADD_MONTHS(SYSDATE, 10) FROM DUAL;

SELECT SYSDATE, ADD_MONTHS(SYSDATE, 10) FROM DUAL;

SELECT SYSDATE, NEXT_DAY(SYSDATE,'SEXTA') FROM DUAL;

// ULTIMO DIA DO MES
SELECT SYSDATE, LAST_DAY(SYSDATE) FROM DUAL;

// PAGA O PRIMEIRO DIA
SELECT SYSDATE, TRUNC(SYSDATE, 'YEAR') FROM DUAL;

SELECT SYSDATE + 200, TRUNC(SYSDATE + 200, 'YEAR') FROM DUAL;

SELECT SYSDATE + 200, ROUND(SYSDATE + 200, 'YEAR') FROM DUAL;

SELECT SYSDATE , TRUNC(SYSDATE, 'YEAR') FROM DUAL;