 
 SELECT NOME FROM TABELA_DE_CLIENTES;
 
 
 // FUNÇÕES DE STRING
 
 SELECT NOME, LOWER(NOME) FROM TABELA_DE_CLIENTES;
 
SELECT NOME, LOWER(NOME),UPPER(NOME) FROM TABELA_DE_CLIENTES;

SELECT NOME_DO_PRODUTO FROM TABELA_DE_PRODUTOS;

// COLOCANDO MAIUSCULA TODO INICIO DE DE PALAVRA
SELECT NOME_DO_PRODUTO, INITCAP(NOME_DO_PRODUTO) FROM TABELA_DE_PRODUTOS;


SELECT ENDERECO_1,BAIRRO FROM TABELA_DE_CLIENTES;

// JUNTAR 
SELECT ENDERECO_1,BAIRRO, CONCAT(ENDERECO_1,BAIRRO) FROM TABELA_DE_CLIENTES;

SELECT ENDERECO_1,BAIRRO, CONCAT(CONCAT(ENDERECO_1,' - '),BAIRRO) FROM TABELA_DE_CLIENTES;

SELECT ENDERECO_1 || ' ' || BAIRRO || ' ' || CIDADE || ' ' || ESTADO || ' - ' || CEP FROM TABELA_DE_CLIENTES;


SELECT NOME_DO_PRODUTO, LPAD(NOME_DO_PRODUTO,70,'*') FROM TABELA_DE_PRODUTOS;

SELECT NOME_DO_PRODUTO, RPAD(NOME_DO_PRODUTO,70,'*') FROM TABELA_DE_PRODUTOS;

// PEGANDO CARECTERES DE UMA STRING
SELECT NOME_DO_PRODUTO, SUBSTR(NOME_DO_PRODUTO,3,5) FROM TABELA_DE_PRODUTOS;

// SE CONTEM UM STRING ESPECIFICO NO TEXTO, retorna a pocisão da string.
SELECT NOME_DO_PRODUTO, INSTR(NOME_DO_PRODUTO,'Campo') FROM TABELA_DE_PRODUTOS;


SELECT NOME, INSTR(NOME,'Mattos') FROM TABELA_DE_CLIENTES;

SELECT NOME FROM TABELA_DE_CLIENTES WHERE INSTR(NOME,'Mattos') <> 0;



// DUAL TABELA QUE NÃO EXISTE
SELECT '  VICTORINO ' FROM DUAL;

SELECT '  VICTORINO ' AS X,LTRIM('  VICTORINO ') AS Y FROM DUAL;

SELECT '  VICTORINO  ' AS X,LTRIM('  VICTORINO  ') AS Y, RTRIM('  VICTORINO  ') AS Y,
TRIM('  VICTORINO  ') AS Z FROM DUAL;

SELECT NOME_DO_PRODUTO, REPLACE(NOME_DO_PRODUTO, 'Litro', 'L') FROM TABELA_DE_PRODUTOS;

SELECT NOME_DO_PRODUTO, REPLACE(REPLACE(NOME_DO_PRODUTO, 'Litro', 'L'),'Ls','L') FROM TABELA_DE_PRODUTOS;


// data

//to_char vai converter data em texto
//to_date vai converter texto em data
// SYSDATE HORA E O DIA ATUAL 
// MONTHS_BETWEEN - VOCE COLOCA DUAS DATA E ELE CALCULA O NUMERO DE MESES ENTRE ESSAS DATAS
// ADD_MONTHS - ADICIONAR NÚMERO DE MESES 
// NEXT_DAY A DATA PROXIMO DIA DA SEMANA EXEMPLO DISSER UMA DATA E A SEMANA ELE VAI RETORNAR A DATA CORREPODENTE A SEMANA.
// LAST_DAY O ULTIMO DIA DO MÊS
// TRUNC ELE VAI PEGAR UMA DATA HORAS E EXIBIR SOMENTE A DATA DIA MES E ANO
// ROUND ARRENDENDASSE A DATA 

// D- DIA DA SEMANA
// DD- DIA DO MÊS
// DDD-NÚMERO DO DIA NO ANO
// DAY - DIA POR EXTENSO

// MM- MÊS DO ANO
//MON - MÊS ABREVIADO
// MONTH - MÊS POR EXTENSO

//YYYY - ANO COM 4 DÍGITOS
//YY - ANO COM DOIS DÍGITOS

// HH - HORA COM DOIS DIGITOS
// HH12 - HORA DE 0 A 12
// HH24 - HORA DE 0 A 24
// MI MINUTO
//SS - SEGUNDO
// SÍMBOLO DE SEPARADOR DA DATA - / * ,/OU UM TEXTO QUALQUER


